name: Cypress Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with default config
        run: npx cypress run --config-file cypress.config.js
        env:
          CI: true

      - name: List default report files
        run: |
          echo "Listing default report files..."
          ls -la cypress/reports || echo "cypress/reports directory does not exist"

      - name: Clean previous custom reports
        run: rm -rf cypress/reports/custom

      - name: Run Cypress tests with custom config
        run: npx cypress run --config-file cypress.config.custom.js
        env:
          CI: true

      - name: List custom report files
        run: |
          echo "Listing custom report files..."
          ls -la cypress/reports/custom || echo "cypress/reports/custom directory does not exist"

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports
          publish_branch: gh-pages
