name: Cypress Tests and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Cucumber
        run: npm test
        env:
          CI: true

      - name: List report files
        run: |
          echo "Listing report files..."
          ls -la cypress/reports

      - name: Check for JSON report files
        run: |
          echo "Checking for JSON report files..."
          if [ -z "$(ls -A cypress/reports/*.json 2>/dev/null)" ]; then
            echo "No JSON report files found!";
            exit 1;
          fi

      - name: Clean previous reports
        run: rm -rf cypress/reports/html

      - name: Merge and generate HTML report
        run: |
          echo "Merging and generating HTML report..."
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/merged-report.json || exit 1
          npx marge cypress/reports/merged-report.json -o cypress/reports/html || exit 1
        env:
          CI: true

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
          publish_branch: gh-pages
