name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests with Cucumber
        run: npm test
        env:
          CI: true

      - name: Check and List HTML report files
        run: |
          echo "Listing report files..."
          ls -la cypress/reports/html || echo "cypress/reports/html directory does not exist"
          echo "Checking for HTML report files..."
          if [ -z "$(ls -A cypress/reports/html/*.html 2>/dev/null)" ]; then
            echo "No HTML report files found!"
            exit 1
          fi

      - name: Rename report.html to index.html
        run: mv cypress/reports/html/report.html cypress/reports/html/index.html

      - name: Add .nojekyll file
        run: echo > cypress/reports/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress/reports/html
          publish_branch: gh-pages

      - name: Verify Deployment
        run: |
          echo "Listing deployed files..."
          ls -la ./cypress/reports/html || echo "No files deployed"
